### PR TITLE
Fix: neonite communism DLC

### PR DESCRIPTION
**Pull request by martvdm**

### CODE REVIEW

**Comment by Beat-YT** [comment]
This won't even work because of modified endpoints

**Comment by Kyiro** [comment]
L + Ratio + Communism sucks

**Comment by PeQuLeaks** [comment]
pull it bro, it gon work

**Comment by timjans01** [comment]
its godly

**Comment by martvdm** [comment]
> pull it bro, it gon work

I agree with this statement

**Comment by FortniteFevers** [comment]
Amazing work bro, 10/10

**Comment by martvdm** [comment]
> Amazing work bro, 10/10

I know I know

**Comment by martvdm** [comment]
> Amazing work bro, 10/10

Thankyou

**Comment by timjans01** [comment]
Ye it’s good

**Comment by Beat-YT** [comment]
Bruh

**Pull request closed without merging**
