### PR TITLE
XMPP Config, removing .NET fix from readme, spelling mistake

### PR DESCRIPTION
**Pull request by Milxnor**
This time I tested it, one issue is that it takes like 5-10 seconds for the bot to get online, I don't know if this is normal.

### CODE REVIEW

**Review by Beat-YT — CHANGES_REQUESTED** [review]
Win is just the platform the bot is running on. like of it was a real player. I don't want to have a useless var for it

**Review by Beat-YT — CHANGES_REQUESTED** [review]
SilverLauncher Run on c#

**Review by Beat-YT — CHANGES_REQUESTED** [review]
BotCid is useless since it will copy the use skin

**Comment by Milxnor** [comment]
1. It affects the icon in lobby
2. didnt know
3. ok srry

**Pull request closed without merging**
