### PR TITLE
Perm Backend fix for connection error on launch

### PR DESCRIPTION
**Pull request by HybridFNBR**
hopefully this stays working for upcoming updates

### CODE REVIEW

**Comment by timjans01** [comment]
How to download neonite?!?!?

**Comment by HybridFNBR** [comment]
Install the latest version of [Node.js](https://nodejs.org/en/download/current/).
(Download the latest [.NET Runtime](https://dotnet.microsoft.com/download) if NeoniteV2 is not working for you.)
Download the [source code](https://github.com/NeoniteDev/NeoniteV2/releases).
Extract the source code.
Open run.bat, it should say [Neonite]: v2.* is listening on port 5595! (Do not close this while running Neonite V2!)
Download the [launcher](https://github.com/NeoniteDev/Carbon/releases/download/1.30/Carbon.zip).
Extract the launcher and open Carbon.exe.
Type in your username (don't use any special characters or spaces.)
press enter and enjoy

**Comment by Beat-YT** [comment]
Neonite v3 👀

**Comment by Beat-YT** [comment]
This will 100% break

**Comment by HybridFNBR** [comment]
thus why i said temp 😉

**Pull request closed without merging**
